version: '3.8'

services:
  contador-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=contador-db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=counterdb
    depends_on:
      - contador-db
    networks:
      - app-network
    volumes:
      - .:/app  # Esto monta todo el proyecto en el contenedor, incluyendo 'templates' y 'static'

  contador-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: counterdb
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/mysql

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
